views/category.py
from flask import (Blueprint, render_template,
                   url_for, request, redirect, jsonify, flash)
from .initdb import session
from models.model import Sport, SportItem
from flask import session as login_session
from functools import wraps

category = Blueprint('category', __name__)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' in login_session:
            return f(*args, **kwargs)
        else:
            flash('You are not allowed to access there')
            return redirect('/login')
    return decorated_function


@category.route('/')
@category.route('/catalog')
def catalog():
    """
    lists all sports catagories
    """
    sport_catalog = session.query(Sport).all()
    items = session.query(SportItem).order_by(SportItem.id.desc()).all()
    return render_template('sports/catalog.html', catalog=sport_catalog,
                           items=items)


@category.route('/catalog/new', methods=['GET', 'POST'])
@login_required
def new():
    """
    create new sport
    """
    if(request.method == "POST"):
        name = request.form['name']
        sport = Sport()
        sport.name = name
        sport.user_id = login_session['user_id']
        session.add(sport)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('sports/new.html')


@category.route('/catalog/<int:sport_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(sport_id):
    """
    edit sport
    """
    sport = session.query(Sport).filter_by(id=sport_id).one_or_none()
    if(sport.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST" and sport is not None):
        name = request.form['name']
        sport.name = name
        session.add(sport)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('sports/edit.html', sport=sport)


@category.route('/catalog/<int:sport_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(sport_id):
    """
    deletes sport
    """
    sport = session.query(Sport).filter_by(id=sport_id).one_or_none()
    if(sport.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST" and sport is not None):
        session.query(SportItem).filter_by(sport_id=sport_id).delete()
        session.delete(sport)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('sports/delete.html', sport=sport)

# Json API to view the whole catalog


@category.route('/catalog/JSON')
def catalogJSON():
    """
    makes a json of present catalog
    """
    sports = session.query(Sport).all()
    sport_list = []
    for sport in sports:
        sport_dict = {}
        sport_dict['id'] = sport.id
        sport_dict['name'] = sport.name
        items = session.query(SportItem).filter_by(sport_id=sport.id).all()
        sport_dict['items'] = [i.serialize for i in items]
        sport_list.append(sport_dict)
    return jsonify(catalog=sport_list)


@category.route('/catalog/item/<int:item_id>/JSON')
def itemJSON(item_id):
    """
    sends a json of a item
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    if(item is None):
        return jsonify(response='item not found')
    else:
        return jsonify(item=item.serialize)

views/item.py
from flask import (Blueprint, render_template,
                   url_for, request, redirect, flash)
from .initdb import session
from flask import session as login_session
from models.model import Sport, SportItem
from functools import wraps

item = Blueprint('item', __name__)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' in login_session:
            return f(*args, **kwargs)
        else:
            flash('You are not allowed to access there')
            return redirect('/login')
    return decorated_function


@item.route('/catalog/<int:sport_id>/item/show')
def show(sport_id):
    """
    list all items of a particular sport
    """
    items = session.query(SportItem).filter_by(sport_id=sport_id)
    return render_template('items/show.html', sport_id=sport_id, items=items)


@item.route('/catalog/item/<int:item_id>/view')
def view(item_id):
    """
    view one item
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    return render_template('items/view.html', item=item)


@item.route('/catalog/<int:sport_id>/item/new', methods=['GET', 'POST'])
@login_required
def new(sport_id):
    """
    create new sport
    """
    sport = session.query(Sport).filter_by(id=sport_id).one_or_none()
    if(request.method == "POST"):
        item = SportItem()
        item.name = request.form['name']
        item.description = request.form['description']
        item.price = request.form['price']
        item.sport = sport
        item.user_id = login_session['user_id']
        session.add(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/new.html', sport=sport)


@item.route('/catalog/item/<int:item_id>/edit',
            methods=['GET', 'POST'])
@login_required
def edit(item_id):
    """
    edit sport item
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    if(item.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST"):
        item.name = request.form['name']
        item.description = request.form['description']
        item.price = request.form['price']
        session.add(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/edit.html', item=item)


@item.route('/catalog/item/<int:item_id>/delete',
            methods=['GET', 'POST'])
@login_required
def delete(item_id):
    """
    deletes a item of a sport
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    if(item.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST"):
        # remove sport item and commmit to database
        session.delete(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/delete.html', item=item)

templates/sports/catalog.html
{% include 'header.html' %}
<div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Categories</span>
    <nav class="mdl-navigation">
        {% for sport in catalog %}
        <a class="mdl-navigation__link" href="{{url_for('item.show',sport_id=sport.id)}}">
            {{ sport.name }}</a>
        {% endfor %}
    </nav>
</div>
<main class="mdl-layout__content">
    <div class="content mdl-grid">
        {% for item in items %}
        <div class="mdl-cell mdl-cell--3-col">
            <div class="demo-card-square mdl-card mdl-shadow--2dp">
                <div class="mdl-card__title mdl-card--expand"></div>
                <div class="mdl-card__supporting-text">
                    {{item.name}} ({{item.sport.name}}) ${{item.price}}
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                    href="{{url_for('item.view', item_id=item.id)}}">
                    See more
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% include 'footer.html'%}

templates/sports/delete.html
{% include 'header2.html' %}
<form method="post" action="{{ url_for('category.delete',sport_id = sport.id)}}">
    <h4>Are you sure you want to delete {{ sport.name }} ?</h4>
    <button type="submit">Yes</button>
</form>
{% include 'footer.html' %}

templates/sports/edit.html
{% include 'header2.html' %}
<form method="post" action="{{ url_for('category.edit',sport_id = sport.id)}}">
    <label>Name:
        <input type="text" name="name" placeholder="{{ sport.name }}">
    </label>
    <button type="submit">Submit</button>
</form>
{% include 'footer.html' %}

templates/sports/new.html
{% include 'header2.html' %}
<form method="post" action="{{ url_for('category.new')}}">
    <label>Name:
        <input type="text" name="name">
    </label>
    <button type="submit">Submit</button>
</form>
{% include 'footer.html' %}