views/item.py
from flask import (Blueprint, render_template,
                   url_for, request, redirect, flash)
from .initdb import session
from flask import session as login_session
from models.model import Sport, SportItem
from functools import wraps

item = Blueprint('item', __name__)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' in login_session:
            return f(*args, **kwargs)
        else:
            flash('You are not allowed to access there')
            return redirect('/login')
    return decorated_function


@item.route('/catalog/<int:sport_id>/item/show')
def show(sport_id):
    """
    list all items of a particular sport
    """
    items = session.query(SportItem).filter_by(sport_id=sport_id)
    return render_template('items/show.html', sport_id=sport_id, items=items)


@item.route('/catalog/item/<int:item_id>/view')
def view(item_id):
    """
    view one item
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    return render_template('items/view.html', item=item)


@item.route('/catalog/<int:sport_id>/item/new', methods=['GET', 'POST'])
@login_required
def new(sport_id):
    """
    create new sport
    """
    sport = session.query(Sport).filter_by(id=sport_id).one_or_none()
    if(request.method == "POST"):
        item = SportItem()
        item.name = request.form['name']
        item.description = request.form['description']
        item.price = request.form['price']
        item.sport = sport
        item.user_id = login_session['user_id']
        session.add(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/new.html', sport=sport)


@item.route('/catalog/item/<int:item_id>/edit',
            methods=['GET', 'POST'])
@login_required
def edit(item_id):
    """
    edit sport item
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    if(item.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST"):
        item.name = request.form['name']
        item.description = request.form['description']
        item.price = request.form['price']
        session.add(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/edit.html', item=item)


@item.route('/catalog/item/<int:item_id>/delete',
            methods=['GET', 'POST'])
@login_required
def delete(item_id):
    """
    deletes a item of a sport
    """
    item = session.query(SportItem).filter_by(id=item_id).one_or_none()
    if(item.user_id != login_session['user_id']):
        flash('You are not authorized')
        return redirect(url_for('category.catalog'))
    if(request.method == "POST"):
        # remove sport item and commmit to database
        session.delete(item)
        session.commit()
        return redirect(url_for('category.catalog'))
    else:
        return render_template('items/delete.html', item=item)

templates/items/delete.html
{% include 'header2.html' %}
<form method="post" action="{{ url_for('item.delete',item_id = item.id)}}">
    <h4>Are you sure you want to delete {{ item.name }} ?</h4>
    <button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
         type="submit">Yes</button>
</form>
{% include 'footer.html' %}

templates/items/edit.html
{% include 'header2.html' %}
<div class="mdl-grid max-width">
    <div class="edit-div mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <form method="post" action="{{ url_for('item.edit', item_id=item.id)}}">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" placeholder="{{item.name}}" type="text" id="1" name="name"/>
                <label class="mdl-textfield__label" for="1">Name..</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <textarea class="mdl-textfield__input" type="text" rows= "3" id="2"
                    name="description" ></textarea>
                <label class="mdl-textfield__label" for="2">Description...</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" name="price" id="3"/>
                <label class="mdl-textfield__label" for="3">Price...</label>
                <span class="mdl-textfield__error">Input is not a number!</span>
            </div>

            <p>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                type="submit">Submit</button>
            </p>
        </form>
    </div>
</div>
{% include 'footer.html' %}

templates/items/new.html
{% include 'header2.html' %}
<div class="mdl-grid max-width">
    <div class="edit-div mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <h3>Add a new item for {{sport.name}}</h3>
        <form method="post" action="{{ url_for('item.new', sport_id=sport.id)}}">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="1" name="name"/>
                <label class="mdl-textfield__label" for="1">Name..</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <textarea class="mdl-textfield__input" type="text" rows= "3" id="2"
                    name="description" ></textarea>
                <label class="mdl-textfield__label" for="2">Description...</label>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" name="price" id="3"/>
                <label class="mdl-textfield__label" for="3">Price...</label>
                <span class="mdl-textfield__error">Input is not a number!</span>
            </div>

            <p>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                type="submit">Submit</button>
            </p>
        </form>
    </div>
</div>
{% include 'footer.html' %}

templates/items/show.html
{% include 'header2.html' %}
<main class="mdl-layout__content">
    <span class="bold-text">Add new item ?</span>
    <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent"
    href="{{url_for('item.new', sport_id=sport_id)}}">Add Item</a>
    <div class="content mdl-grid">
        {% for item in items %}
        <div class="mdl-cell mdl-cell--3-col">
            <div class="demo-card-square mdl-card mdl-shadow--2dp">
                <div class="mdl-card__title mdl-card--expand"></div>
                <div class="mdl-card__supporting-text">
                    {{item.name}} ({{item.sport.name}}) ${{item.price}}
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                    href="{{url_for('item.view', item_id=item.id)}}">
                    See more
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% include 'footer.html'%}

templates/items/view.html
{% include 'header2.html' %}
<section>
    <div class="mdl-grid max-width mdl-card mdl-shadow--4dp">
        <div class="mdl-cell mdl-cell--12-col">
            <h2>{{item.name}}</h2>
            <p>{{item.description}}</p>
            <p>${{item.price}}</p>
            <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                href="{{url_for('item.edit', item_id=item.id)}}">
                Edit
            </a>
            <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                href="{{url_for('item.delete', item_id=item.id)}}">
                Delete
            </a>
        </div>
    </div>
</section>
{% include 'footer.html' %}